apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.30.0
    options:
      log-level: debug
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  annotations:
    'consul.hashicorp.com/connect-inject': 'false'
